### ISSUE TITLE
关于07L复现差距大的问题

### ISSUE THREAD

**Issue by wengwenchao123** [LMissher/STWave#10]
大佬，我看过您最早发在arxiv上的版本，里面有07M和07L的效果，我最近在拿STWave做baseline，想画一个12步误差的折线图，其他的数据集都复现出来了，但是在07L上我复现出来的效果差距很大，平均误差MAE在3.11左右，当时你论文上写的效果是2.88，您当时是怎么训练的，有没有当时的每步误差结果，我好记录一下用来画图，谢谢

**Comment by LMissher** [comment]
感谢使用STWave作为baseline，之前的log因为升学没了。我这两天跑一下然后把结果和对应设置贴出来。

**Comment by wengwenchao123** [comment]
好的，麻烦大佬了，我现在就缺这个折线图了

**Comment by LMissher** [comment]
不麻烦应该的，那我加快跑一下尽量今天po出来

**Comment by LMissher** [comment]
testing begin....
step 1, mae: 1.3896, rmse: 2.4282, mape: 0.0306
step 2, mae: 1.9181, rmse: 3.5520, mape: 0.0437
step 3, mae: 2.2965, rmse: 4.3933, mape: 0.0541
step 4, mae: 2.5983, rmse: 5.0811, mape: 0.0631
step 5, mae: 2.8099, rmse: 5.5525, mape: 0.0697
step 6, mae: 3.0093, rmse: 6.0067, mape: 0.0759
step 7, mae: 3.1642, rmse: 6.3380, mape: 0.0809
step 8, mae: 3.3081, rmse: 6.6297, mape: 0.0859
step 9, mae: 3.4332, rmse: 6.8754, mape: 0.0900
step 10, mae: 3.5180, rmse: 7.0627, mape: 0.0924
step 11, mae: 3.6151, rmse: 7.2487, mape: 0.0952
step 12, mae: 3.7056, rmse: 7.4104, mape: 0.0978
average, mae: 2.8972, rmse: 5.9110, mape: 0.0733
testing end....

**Comment by LMissher** [comment]
当前版本确实跑不出小于3的，我用仓库最初版本试了下，上面是跑出来的结果。

应该是因为PyWavelets和pytorch_wavelets的实现差异导致当前版本结果较差。

**Comment by wengwenchao123** [comment]
好，谢谢大佬

**Comment by LMissher** [comment]
应该滴~
