### ISSUE TITLE
关于复现LSGCN

### ISSUE THREAD

**Issue by wkq-wukaiqi** [LMissher/STWave#11]
作者您好，看到您论文中报告了LSGCN的结果，请问LSGCN的代码有开源的pytorch实现吗，我只找到了这个tensorflow实现的版本：https://github.com/helanzhu/LSGCN/tree/master

**Comment by LMissher** [comment]
LSGCN的结果我是参考STG-NCDE论文里的，也不太清楚是否有torch版本的实现。

**Comment by wkq-wukaiqi** [comment]
感谢回复
