### ISSUE TITLE
请问大佬，data 中的 adj.npy 文件是如何生成的？

### ISSUE THREAD

**Issue by hczs** [LMissher/STWave#12]
翻了下之前的 issue，adj.npy 好像是后来代码更新过后使用的新文件；
根据相关 issue，生成思路参考了DCRNN(https://github.com/liyaguang/DCRNN/blob/master/scripts/gen_adj_mx.py) 然后也试着自己生成 adj.npy，但是跟大佬的文件不一样，加载到模型里面，跑出来的loss第一轮都是50多，后面到30左右就不下降了；
所以想请教一下大佬生成adj.npy的函数是否还保留着，想要复现一下。万分感激！

**Comment by LMissher** [comment]
loss是包含了原始时间序列与低频部分的两个内容，所以我记得30多应该是正常的。最后test的结果应该与论文差别不大。

**Comment by hczs** [comment]
> loss是包含了原始时间序列与低频部分的两个内容，所以我记得30多应该是正常的。最后test的结果应该与论文差别不大。

非常感谢作者及时回复，跑完test结果确实接近论文水平，问题已解决！
