### ISSUE TITLE
关于STWave在BasicTS和当前代码上的疑问

### ISSUE THREAD

**Issue by wengwenchao123** [LMissher/STWave#14]
大佬，有个事情我想询问一下，因为我现在手上工作的原因，我在对STWave的使用全图注意力（就是去掉ESGAT后使用所有节点的注意力）的变体进行测试
代码如下
`

        if self.which_to_use == "use_ESGAT":
            # # use gat results to reduce Q
            K_expand = K.unsqueeze(-3).expand(B, T, N, N, D)
            K_sample = K_expand[:, :, torch.arange(N).unsqueeze(1), self.la, :]
            Q_K_sample = torch.matmul(Q.unsqueeze(-2), K_sample.transpose(-2, -1)).squeeze()

            Sampled_Nodes = int(self.s * math.log(N, 2))
            M = self.proj(Q_K_sample).squeeze(-1)
            M_top = M.topk(Sampled_Nodes, sorted=False)[1]

            # use the reduced Q to calculate Q_K
            Q_reduce = Q[torch.arange(B)[:, None, None],
                       torch.arange(T)[None, :, None],
                       M_top, :]
            Q_K = torch.matmul(Q_reduce, K.transpose(-2, -1))

            Q_K /= (self.d ** 0.5)

            attn = torch.softmax(Q_K, dim=-1)

            # copy operation
            cp = attn.argmax(dim=-2, keepdim=True).transpose(-2, -1)

            value = torch.matmul(attn, V).unsqueeze(-3).expand(B, T, N, M_top.shape[-1], V.shape[-1])[
                    torch.arange(B)[:, None, None, None],
                    torch.arange(T)[None, :, None, None],
                    torch.arange(N)[None, None, :, None], cp, :].squeeze(-2)
        elif self.which_to_use == "use_full_GAT":
            K = K.transpose(
                -1, -2
            )  # (num_heads * batch_size, ..., head_dim, src_length)

            attn_score = (
                                 Q @ K
                         ) / (self.d ** 0.5)  # (num_heads * batch_size, ..., tgt_length, src_length)

            attn_score = torch.softmax(attn_score, dim=-1)
            value = attn_score @ V  # (num_heads * batch_size, ..., tgt_length, head_dim)
`

在测试过程中我发现一个很奇怪的地方，一开始我是看到你的模型集成到BasicTS上了，所以就是用那个框架来进行训练和比较，发现在BasicTS上，use_full_GAT变体所需要的显存明显小于你论文中报告的情况，所以我后来在你代码上面也测了一下，发现两者差距超大。
以08为例，batchsize为64的情况下，在BasicTS上use_full_GAT变体只需要6.04个G，使用ESGAT需要5.84GB,但是在你的代码里面需要10个G，使用ESGAT要6GB多一点，其差距很明显，其他几个节点更多的数据集更明显，这个是可能由于什么原因导致的呢？

另外用STWave的框架跑，确实存在训练不稳定的情况，可能要碰运气才能复现，在BasicTS下，你的模型的收敛是比较稳定的，基本每次都能复现，这个是有什么原因吗？（注，为了明确看到主体模块的loss，我把两边框架下的长期分量的loss都去掉了）

因为我现在的工作过是跟显存和训练速度相关的内容，所以对这个比较看重。我现在的测试效果是以BasicTS来的，但是他的显存占用确实感觉不合理，我个人是觉得你框架下的显存是更可信的，但训练稳定度是BasicTS高。

期待你的回应，谢谢

**Comment by LMissher** [comment]
wenchao你好，

显存的差异应该是参数设置不一致所导致，在多头注意力（也即当前仓库设置）下，ESGAT的显存优势将被突出。

不过，多头也可能是训练不稳定的原因。

仅供参考，希望能有帮助~

**Comment by wengwenchao123** [comment]
> wenchao你好，
> 
> 显存的差异应该是参数设置不一致所导致，在多头注意力（也即当前仓库设置）下，ESGAT的显存优势将被突出。
> 
> 不过，多头也可能是训练不稳定的原因。
> 
> 仅供参考，希望能有帮助~

嗯，确定了，关于显存的差异是因为多头注意力导致的，没想到这个影响会这么大，性能的话我需要测试一下，看看是不是这个引起的，谢谢大佬
