### ISSUE TITLE
关于Figure 4

### ISSUE THREAD

**Issue by ZhangYuan1998** [LMissher/STWave#2]
你好，想请教下论文里这个图是怎么画的呀？
![image](https://user-images.githubusercontent.com/102887477/196864821-6647a127-99ef-40d3-8805-7d83f0c8a011.png)

**Comment by LMissher** [comment]
你好我是将一天的预测与细粒度的小时预测先画出来，然后再一起放到visio里画出最后的图

**Comment by ZhangYuan1998** [comment]
非常感谢！
