### ISSUE TITLE
请问一下data中的adjgat.npy是做什么的，还有这个是怎么生成的

### ISSUE THREAD

**Issue by wengwenchao123** [LMissher/STWave#3]
我自己看了论文，但是还是没有看懂adjgat.np作用，按论文的理解，我以为是对QK镜像topk来选取其中的最重要的节点来进行最后计算，但是代码里面是用了adjgat.npy来进行升维，这个不在论文里面，能不能详细解释一下。

**Comment by LMissher** [comment]
你好，adjgat.npy这个文件是用来计算GAT的，然后是选择的每个节点的邻近节点得到的。

GAT我暂时没有看到很好的时空实现方式，所以就手写了一下，其中expand操作并没有额外的空间开销，可以参考https://discuss.pytorch.org/t/torch-repeat-and-torch-expand-which-to-use/27969。

过几天我会把icde版本上传arxiv。希望能对你有帮助。

**Comment by wengwenchao123** [comment]
那这个adjgat.npy的邻近节点是怎么得到的，是根据数据集自带的adj.npy做出来的吗，可我记得在adj.npy中好像有个别节点是没有邻居节点的

**Comment by LMissher** [comment]
是的，根据adj做出来的，确实会有几个孤立点。对孤立点随机选择了邻居，也算是不足之处

**Comment by ShiYue-oo** [comment]
请问有求解adjgat的代码吗，上面那个链接失效了

**Comment by LMissher** [comment]
上面那个链接不是求解adjgat的代码，是计算GAT的来着。

求解adjgat的话，用最短路算法就行。

**Comment by ShiYue-oo** [comment]
我求出来前几行是这样的
![image](https://github.com/LMissher/STWave/assets/118509758/18ee02ef-cb9e-4b2c-b3c2-bba276572d4f)
但是您的adjgat前几行为：
![image](https://github.com/LMissher/STWave/assets/118509758/cf04e887-ef43-433e-93c7-d157fb7b5d54)

**Comment by LMissher** [comment]
不是距离最近的七个点，为了防止局部点信息过于相似，我们当时是从距离最接近的一些点中挑出了log个点

**Comment by ShiYue-oo** [comment]
好的，多谢多谢

**Comment by LMissher** [comment]
应该的~
