### ISSUE TITLE
你好 显示维度问题怎么办

### ISSUE THREAD

**Issue by OvOYu** [LMissher/STWave#4]
![image](https://github.com/LMissher/STWave/assets/107761563/92ac3ecc-dc64-47c5-85d8-765dff34fdfd) 我使用的是原数据提供的npz文件 是文件问题吗

**Comment by LMissher** [comment]
可以看一下原始文件的维度，我用的文件维度是[batch size,timeslices,node,1]。如果输入的不一样可以做相应的调整。

**Comment by LMissher** [comment]
可以看一下原始文件的维度，我用的文件维度是[batch size,timeslices,node,1]。如果输入的不一样可以做相应的调整。

**Comment by OvOYu** [comment]
需要对原始文件进行处理吗 flow.npz文件不是原始的PEMS08.npz文件吗

**Comment by LMissher** [comment]
把原始的pems08扩张一个维度应该就可以，不是原始的

**Comment by OvOYu** [comment]
![image](https://github.com/LMissher/STWave/assets/107761563/172dd47f-3cc2-4c75-8512-6c4f3300d848)
w我的理解是原始数据是（B.T,C），你的意思是取c的第1维，变为（b，t，1）在压缩变为b，t请问对吗 可以跑代码我这样修改后。打印出来的Traffic维度是(17856, 170)，请问对吗

**Comment by OvOYu** [comment]
如果先扩充在压缩，那么数据还是3维

**Comment by LMissher** [comment]
是的，取第一维就行。开始说错了。TNC取流量那个维度就行。

**Comment by LMissher** [comment]
取出来就是TN，时间和节点维度，17856和170是对的

**Comment by OvOYu** [comment]
谢谢您的回复

**Comment by OvOYu** [comment]
![image](https://github.com/LMissher/STWave/assets/107761563/1c5376f4-596e-451c-afe6-9b756759338f)
请问一下这个代码是什么意思啊

**Comment by OvOYu** [comment]
谢谢您，祝您一切顺利！

**Comment by LMissher** [comment]
应该的，不客气~

**Comment by OvOYu** [comment]
average, mae: 13.8737, rmse: 24.9807, mape: 0.1037
training end....
testing begin....
step 1, mae: 12.0204, rmse: 19.8012, mape: 0.0829
step 2, mae: 12.5090, rmse: 21.0151, mape: 0.0845
step 3, mae: 12.9055, rmse: 21.8563, mape: 0.0877
step 4, mae: 13.3394, rmse: 23.0632, mape: 0.0900
step 5, mae: 13.4891, rmse: 23.3341, mape: 0.0908
step 6, mae: 13.8148, rmse: 24.1966, mape: 0.0929
step 7, mae: 14.0664, rmse: 24.6971, mape: 0.0938
step 8, mae: 14.1633, rmse: 24.7633, mape: 0.0953
step 9, mae: 14.3132, rmse: 24.9935, mape: 0.0970
step 10, mae: 14.4646, rmse: 25.5353, mape: 0.0963
step 11, mae: 14.6737, rmse: 25.8411, mape: 0.0979
step 12, mae: 14.8401, rmse: 26.0219, mape: 0.0996
average, mae: 13.7166, rmse: 23.8364, mape: 0.0924

**Comment by OvOYu** [comment]
这是我在pems08上训练了两次，两次都是这个结果。我发现mae比论文里的13.42高了差不多0.3，其他两个指数也都略微偏高一点，请问下您这种情况该如何解决呢 有好的调参方案吗 谢谢

**Comment by OvOYu** [comment]
谢谢您，感谢，祝好！

**Comment by LMissher** [comment]
不客气

**Comment by OvOYu** [comment]
你好，请问下能分享下您使用的PEMSD7M/L文件吗 感谢！

**Comment by OvOYu** [comment]
STGCN提供的我看都是csv形式

**Comment by LMissher** [comment]
csv文件的话，可以使用pandas读取然后转成numpy格式

**Comment by OvOYu** [comment]
ok 谢谢
