### ISSUE TITLE
数据读取问题

### ISSUE THREAD

**Issue by wengwenchao123** [LMissher/STWave#6]
现在的代码是直接读取flow.npz文件的，但是提供的PEMSD4等数据集仍然是三个特征的，建议把数据读取那边优化一下更方便其他人使用。

这个dtw矩阵没有保存功能吗，发现每跑一次需要等好久生成才行

**Comment by LMissher** [comment]
新的更新优化了数据读取以及新增了TemGraph保存检查功能，感谢宝贵的意见
