### ISSUE TITLE
自己数据集问题

### ISSUE THREAD

**Issue by RJDN1** [LMissher/STWave#7]
作者您好，如果我想用自己的数据集需要更改哪些配置呢？

**Comment by LMissher** [comment]
修改config文件里相应文件地址，节点数目，输入输出长度就行。

此外代码默认输入输出特征为1，如果自己数据集不是1，修改以下两处就行：
https://github.com/LMissher/STWave/blob/801601cf761792cebc26008d6b6cd5d1232dfc8c/lib/utils.py#L72
https://github.com/LMissher/STWave/blob/801601cf761792cebc26008d6b6cd5d1232dfc8c/model/models.py#L321C1-L324C62

**Comment by RJDN1** [comment]
谢谢作者，请问adj文件会影响吗？我的数据不是交通数据，是多参数预测电量问题，想试试效果。

**Comment by LMissher** [comment]
不客气。adj的影响还挺大的，因为要计算一个localGAT，不过也可以随机选择一些节点作为邻居试试看，或者看看能不能根据一些metric构造个adj。

**Comment by RJDN1** [comment]
还有一个问题，作者大大是怎么解决数据泄露的问题的呢？

**Comment by LMissher** [comment]
关于数据泄露可以参考一篇我写的博客，里面讲的应该比较清楚了：https://zhuanlan.zhihu.com/p/676126252

**Comment by RJDN1** [comment]
原来是作者大大写的，膜了

**Comment by LMissher** [comment]
嘿嘿，希望能对你带来帮助

**Comment by RJDN1** [comment]
作者您好
[1）请问现在的代码可以读csv文件吗？
2）4-8的npz文件都是用03的csv文件的那种格式做的吗？里面不需要关于时间的列吗？

**Comment by LMissher** [comment]
1）不可以读取csv文件
2）npz文件都是用的这个网址里下的 https://pan.baidu.com/s/1ZPIiOM__r1TRlmY4YGlolw
3）conf文件或者main文件里是不是把temadj相关的代码删了
