### ISSUE TITLE
关于超参数

### ISSUE THREAD

**Issue by cwtaea** [LMissher/STWave#9]
您好，请问代码中有两个超参数一个是head，一个是dims，它们分别代表的是什么？我的数据集是一个6节点的数据，我生成adj.npy文件后，必须将heads*dims=节点数时程序才可以运行。

**Comment by LMissher** [comment]
代表时间注意力机制的头数和每个头的特征数，也就是heads*dims是模型的特征数。因为模型用了图小波作为位置编码，也就涉及拉普拉斯特征向量和特征值，那么模型的特征维数不会超过图节点个数，所以可能不太适合节点过少的数据集，不过也可以补0。

具体代码可以参考:
https://github.com/LMissher/STWave/blob/19feab9c775bbbc35854930ee8142880aa5d4dbd/lib/graph_utils.py#L59C1-L60C38

**Comment by cwtaea** [comment]
谢谢回复，但是还是不太理解补0的含义，可以详细讲讲嘛

**Comment by cwtaea** [comment]
感谢您的回复，很抱歉给您发了这么多封邮件，希望没有对您造成困扰。
但是我对于您所的补0的处理的含义我还没有理解，可以解释清楚一些嘛。同时，这样会不会对预测效果造成影响。
祝好


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "LMissher/STWave"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月20日(星期一) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LMissher/STWave] 关于超参数 (Issue #9)





 
代表时间注意力机制的头数和每个头的特征数，也就是heads*dims是模型的特征数。因为模型用了图小波作为位置编码，也就涉及拉普拉斯特征向量和特征值，那么模型的特征维数不会超过图节点个数，所以可能不太适合节点过少的数据集，不过也可以补0。
 
具体代码可以参考:
 https://github.com/LMissher/STWave/blob/19feab9c775bbbc35854930ee8142880aa5d4dbd/lib/graph_utils.py#L59C1-L60C38

**Comment by LMissher** [comment]
模型特征数不能太小，对于节点很少的图的小波位置编码就只有repeat或者补0

**Comment by cwtaea** [comment]
尝试在spawave和temwave补0后，会出现一个错误
![1](https://github.com/LMissher/STWave/assets/138765142/51a4ad96-1b92-477e-bc56-e62ffa9b872e)

**Comment by LMissher** [comment]
修改后的代码错误可能需要自己分析下

**Comment by cwtaea** [comment]
感谢帮助！

**Comment by LMissher** [comment]
应该的
